name: Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  
  deploy:
    name: Integration
    runs-on: ubuntu-latest
    steps:

      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
 
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2`

      - name: Maven Clean & Package
        run: mvn -B clean package --file pom.xml

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2.2.0
        with:
          tags: louisonsarlinmagnus/interface:latest
          load: true

      - name: Push
        run: docker push louisonsarlinmagnus/interface:latest
          
          
  sonarcloud:
    name: Analyse SonarCloud
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master branch
      uses: actions/checkout@v2
    
    - name: SonarCloud Scan
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=Projet-Spring-Boot_Interface -Dsonar.organization=projet-spring-boot-interface -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
